---
- name: Install init.lua.
  ansible.builtin.template:
    src: templates/init.lua.j2
    dest: "{{ nvim_dir }}/init.lua"
    mode: "0644"
    force: true

- name: Install config templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    force: false
  loop:
    - src: "templates/lua/config/mappings.lua.j2"
      dest: "{{ config_dir }}/mappings.lua"
    - src: "templates/lua/config/settings.lua.j2"
      dest: "{{ config_dir }}/settings.lua"
