---
- name: Ensure that essential packages are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ neovim_system_packages }}"

- name: Ensure required directories exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ neovim_base_dir }}"
    - "{{ neovim_config_dir }}"
    - "{{ neovim_plugins_dir }}"

- name: Install requirements for language modules.
  ansible.builtin.import_tasks: "modules/main.yml"

- name: Set up LSP
  ansible.builtin.import_tasks: "lsp.yml"
  when: neovim_use_lsp

- name: Set up TreeSitter
  ansible.builtin.import_tasks: "treesitter.yml"
  when: neovim_use_treesitter

- name: Install config files
  ansible.builtin.import_tasks: "config.yml"

- name: Install plugins.
  ansible.builtin.import_tasks: "plugins.yml"

- name: Clone snippets.
  ansible.builtin.import_tasks: "snippets.yml"
  when: neovim_install_snippets
