---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Ensure that essential packages are installed.
  ansible.builtin.package:
    name:
      - git
      - neovim
    state: present
  become: true

- name: Ensure required directories exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ nvim_dir }}"
    - "{{ config_dir }}"
    - "{{ plugins_dir }}"

# Config
- name: Install config files
  ansible.builtin.import_tasks: "config.yml"

# Packer
- name: Install plugins with packer.
  ansible.builtin.import_tasks: "packer.yml"
  when: plugin_manager == "packer"

# LSP
- name: Install LSP
  ansible.builtin.import_tasks: "lsp.yml"
  when: use_lsp

- name: Fail
  ansible.builtin.fail:

# TreeSitter
- name: Install TreeSitter
  ansible.builtin.import_tasks: "treesitter.yml"
  when: use_treesitter
