---
- name: Ensure that essential packages are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ system_packages }}"

- name: Ensure required directories exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ nvim_dir }}"
    - "{{ config_dir }}"
    - "{{ plugins_dir }}"

- name: Install config files
  ansible.builtin.import_tasks: "config.yml"

- name: Install requirements for language modules.
  ansible.builtin.import_tasks: "modules/main.yml"

- name: Install plugins with packer.
  ansible.builtin.import_tasks: "packer.yml"
  when: plugin_manager == "packer"

- name: Install LSP
  ansible.builtin.import_tasks: "lsp.yml"
  when: use_lsp

- name: Install TreeSitter
  ansible.builtin.import_tasks: "treesitter.yml"
  when: use_treesitter

- name: Clone snippets.
  ansible.builtin.import_tasks: "snippets.yml"
  when: install_snippets
