---
- name: Ensure that packer is installed
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
    version: master

- name: Install packer configuration templates
  ansible.builtin.template:
    src: templates/lua/plugins/packer.lua.j2
    dest: "{{ plugins_dir }}/packer.lua"
    mode: "0644"
    force: true
  notify: PackerSync

- name: Copy packer plugin configuration files.
  ansible.builtin.copy:
    src: "files/lua/plugins/{{ item.name }}.lua"
    dest: "{{ plugins_dir }}/{{ item.name }}.lua"
    mode: "0644"
  notify: PackerSync
  loop: "{{ plugins }}"
  when: item.name is defined
