---
- name: Ensure snippets directory exists.
  ansible.builtin.file:
    path: "{{ snippets_dir }}"
    state: directory
    mode: "0755"

- name: Clone snippets repos.
  ansible.builtin.git:
    repo: "{{ snippets_repos }}"
    dest: "{{ snippets_dir }}"
    version: "{{ snippets_version }}"
