---
- name: Ensure snippets directory exists.
  ansible.builtin.file:
    path: "{{ neovim_snippets_dir }}"
    state: directory
    mode: "0755"

- name: Clone snippets repos.
  ansible.builtin.git:
    repo: "{{ neovim_snippets_repo }}"
    dest: "{{ neovim_snippets_dir }}"
    version: "{{ neovim_snippets_version }}"
