---
# directories
neovim_base_dir: ~/.config/nvim

neovim_install_system_packages: false

neovim_colorscheme: nightfox

neovim_plugin_manager: lazy

neovim_use_lsp: true
neovim_use_treesitter: true
neovim_use_wk: true

neovim_overwrite_mappings: false

neovim_use_codeium: false
neovim_use_chatgpt: false
neovim_chatgpt_api_key_cmd: ""

neovim_install_snippets: false
neovim_snippets_repo: git@github.com:dhammafarer/snippets.git
neovim_snippets_version: main
