---
nvim_dir: ~/.config/nvim
plugins_dir: ~/.config/nvim/lua/plugins
config_dir: ~/.config/nvim/lua/config
snippets_dir: ~/.config/nvim/snippets

plugin_manager: packer

use_lsp: true
use_treesitter: true

install_snippets: false
snippets_repo: git@github.com:dhammafarer/snippets.git
snippets_version: main
