---
nvim_dir: ~/.config/nvim
plugins_dir: ~/.config/nvim/lua/plugins
config_dir: ~/.config/nvim/lua/config
snippets_dir: ~/.config/nvim/snippets

colorscheme: nightfox

plugin_manager: lazy

use_lsp: true
use_treesitter: true
use_wk: true

overwrite_mappings: false

use_codeium: false
use_chatgpt: false
chatgpt_api_key_cmd: ""

install_snippets: false
snippets_repo: git@github.com:dhammafarer/snippets.git
snippets_version: main
