---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: debian11
    box: generic/debian11
    cpus: 2
    memory: 512
provisioner:
  name: ansible
verifier:
  name: ansible
